name: todone
description: Analyze your TODOs in code and create a summary

inputs:
  globs:
    description: "Files to analyze, glob patterns supported"
    required: false
    default: "**/*"
  github-token:
    description: "GitHub token to access the repository"
    required: false
    default: "${{ github.token }}"
  dry-run:
    description: "If true, the action will not create issues or comments, only print the summary"
    required: false
    default: "false"
  keyword:
    description: 'Keyword to search for TODOs in the code (default: "@TODO")'
    required: false
    default: "@TODO"
  # *TODO https://github.com/cprecioso/todone/issues/25
  # *TODO https://github.com/cprecioso/todone/issues/24

runs:
  using: "node24"
  main: "dist/bin.js"
