name: Build and check PR

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
      - run: yarn install --immutable

      - name: Build and check
        run: yarn nx run-many -t build,check,build-docs

      - name: Pack packages
        run: |
          folder=$(pwd)/out
          mkdir -p $folder
          yarn workspaces foreach --all --no-private pack --out $folder/%s-%v.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./out/*

      - name: Pack GitHub Action
        run: |
          folder=$(pwd)/github-action
          mkdir -p $folder
          yarn workspace @todone/github-action pack --out $folder/github-action-%v.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: github-action
          path: ./github-action/*

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
