name: Build and check PR

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare

      - run: yarn nx run-many -t build,check,build-docs

      - run: |
          folder=$(pwd)/out
          mkdir -p $folder
          yarn workspaces foreach --all --no-private pack --out $folder/%s-%v.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./out/*

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
