name: Build packages

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: yarn nx run-many -t package:all,build-docs
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: out/*
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
