name: Run release process

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - uses: changesets/action@v1
        id: changesets
        with:
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ github.token }}

    outputs:
      needs-publish: ${{ steps.changesets.outputs.hasChangesets == 'false' }}

  test:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Here is the value:" $VALUE
        env:
          VALUE: ${{ toJson(needs.release.outputs.needs-publish) }}

  test-a:
    needs: release
    runs-on: ubuntu-latest
    if: needs.release.outputs.needs-publish
    steps:
      - run: echo "Hey"

  test-b:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ !needs.release.outputs.needs-publish }}
    steps:
      - run: echo "Ho"

  build:
    needs: release
    uses: ./.github/workflows/build.yaml

  deploy-packages:
    needs: [release, build]
    if: needs.release.outputs.needs-publish

    permissions:
      contents: read
      packages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com/
      - uses: actions/download-artifact@v4
        with:
          name: packages
      - name: Publish packages
        run: |
          for file in ./*; do
            echo "Publishing $package"
            npm publish --tag latest --access public --provenance $file || true
          done
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

  deploy-pages:
    needs: [release, build]
    if: needs.release.outputs.needs-publish

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
