name: Run release process

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - uses: changesets/action@v1
        id: changesets
        with:
          commitMode: github-api
          publish: |
            nx build
            yarn npm publish --tag latest --access public --provenance
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ github.token }}
          NODE_AUTH_TOKEN: ${{ github.token }} }}
      - uses: actions/deploy-pages@v4
        if: steps.changesets.outputs.hasChangesets == 'false'
