name: Run release process

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: googleapis/release-please-action@v4
        id: release

    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}

  publish:
    needs: release
    if: needs.release.outputs.releases_created
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
