name: Todone

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cprecioso/todone-action@v1
        with:
          globs: "**/*"
