name: Todone

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
      - run: yarn install --immutable

      - name: Build action
        run: yarn run nx run @todone/github-action:build

      - name: Run todone
        uses: ./packages/github-action
        with:
          globs: |
            **/*
            !.nx/**/*
            !node_modules/**/*
            !dist/**/*
          keyword: "*TODO"
