name: Todone

on:
  workflow_dispatch:
  schedule:
    - cron: "32 18 * * *" # Every day at a chosen random time
  push:
    branches:
      - main

env:
  # *TODO https://github.com/actions/runner/issues/3600
  # Remove when GitHub Actions supports Node 24 without a workaround
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4

      - uses: actions/setup-node@v6
        with:
          cache: "yarn"
      - run: yarn install --immutable

      - name: Build action
        run: yarn nx run @todone/repo:build

      - name: Run todone
        env:
          NODE_OPTIONS: "--enable-source-maps"
          GITHUB_TOKEN: ${{ github.token }}
        run: yarn todone run
